spring.application.name=connecthub-springboot-react

# MongoDB Connection
spring.data.mongodb.uri=mongodb+srv://pdimalka1979_db_user:NaxELAc2ctl71vYo@cluster0.g34owks.mongodb.net/connecthub?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=connecthub

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

